language: java
jdk:
- oraclejdk8
script: mvn clean deploy
env:
  global:
  - SONATYPE_USERNAME=joseblas
  - secure: "XRvVuXbfpgTuP35aWiSfT+Q+1gVeTKQrPwWCbcd3EFpZoH7pSCoroV7UplXFprXOxcGHL+YGuQuabq/gr+Fb/I8xxQgCtsWALVhA0iN0zsf2T3bTmkhIDmeo7qhKivPTuMHGAsQj2x7cnWd3XKz4tAPObPf/baTC6anqRPZt2ZvlvfGdbCCJ0FpNqIC1GC5uONclvfPVIqGNfYKcoEcRA2Nso4UjeJ9bXZbI/gXrZKbgzlcn2HUt2VfynKaeeVk+CmkSpsCfMGLFIrlQcCS60JNMJGeSFrtdbrOc1x3GMdKzKlLZT3P6+ugcPfO9j4MBhsSQlcXDW6sIhmrMLnKZIIT00PfExo/Ox+sI75xJYfCBrFqQ0rQ1zyjjUQmcHtyYguld9he48GDfRIc3NTAaHchEHohVeL18EMJZNsW1ee9qJovx87JqEwHpb8G8gOcvFRCr3IrqFuBxQFZqkg8B/PZ9qKP4tBHisXp/a87Fi78rdfjO/oGyekJqLRL46ANBKeo5u18GBInTFMMFay2PQzI4XyfYk+9icHIytbBiDej3u2Z/Vikef3ucjlOpKGznsVpLb2iIcvU0Xeee+rqSfISe2lbMiOLzIGcW9YmEPvT/Ms9+htiPxKnAop5S0iBwmFnXnYcPfk4kyyX5E10DqiOMRLaxRm5fHbArg0dNtA0="
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $BUILD_NUMBER" > /dev/null
  2>&1
- git push -q https://$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG --tags
deploy:
  provider: releases
  api_key: 9aML6u6pWr2ZhYWEEhsG
  file_glob: true
  skip_cleanup: true
  on:
    repo: joseblas/baron-greenback
    tags: false
    all_branches: true
branches:
  except:
  - "/^[0-9].[0-9]*/"
